- .circleci/bin/getsecret
- .circleci/config.yml
- aws_lambda/handler.py
- handler.py
- requirements_lambda.txt
- serverless.yml
FPO-139
- Adds sentry package
- Initialise sentry and load SENTRY_DSN
- This is a prerequisite for a private beta
Secrets are never printed to a console:
> FPO-139: Configure sentry

- .circleci/bin/getsecret
- .circleci/config.yml
- .circleci/ec2
- .circleci/ecr
- .pre-commit-config.yaml
- serverless.yml
FPO-183
- This is required to let us know when our lambda function is erroring/taking a long time to execute
> FPO-183: Adds SNS topic and AWS/Lambda Duration and Errors alarm

- .github/pull_request_template.md
- .markdownlint.yaml
- .pre-commit-config.yaml
- README.md
> BAU: Consolidate pre-commit configuration

- inference/infer.py
- serverless.yml
> BAU: Fix device specification

- search-config.toml
- training/train_model.py
BAU
- This is required to help us make decisions about the model and to track progress
> BAU: Fixes loss benchmark output and adds logging

- .circleci/bin/checkbenchmarks
- .circleci/bin/fetchbenchmarks
- Make the fetchbenchmarks script more helpful
- Adds threshold results to checks file
- This enables anyone with access to fetch a given model and compare it to an older one
> BAU: Give more useful information in check_results.json

- aws_lambda/handler.py
- requirements.txt
https://transformuk.atlassian.net/browse/FPO-354
- So that we can more easily see and report on what is being queried
> FPO-354: Adding extra logging

- data_sources/search_references.py
- data_sources/vague_terms.py
- reference_data/brands.csv
- search-config.toml
- train.py
- train_args.py
FPO-329
- This helps the tool handle queries about known brands
> FPO-329: Incorporate brands data

- aws_lambda/handler.py
- data_sources/basic_csv.py
- data_sources/commodities.py
- tests/aws_lambda/test_handler.py
- tests/test_cleaning_pipeline.py
- training/cleaning_pipeline.py
FPO-374
- This enables us to bypass German, Spanish and French descriptions
- Validates non-English descriptions
> FPO-374: Language detection

- .circleci/bin/buildmodel
- .circleci/bin/clearinstances
- .circleci/bin/copyami
- .circleci/bin/getmodelregions
- .circleci/bin/smoketest
- search-config.toml
- serverless.yml
BAU
- Hoist all variables and make them visible
- Handle output of instance creation commands consistently
- Capture status outputs when launching instances to enhance debugging
- Move to local variables to avoid scoping and leakage issues
- Avoid changes to the errexit option where possible by using if for function calls with specific status cases
- Add a case statement to handle different status messages
- This helps give us better feedback on specific multi-region failures
- This makes the scripts less brittle
> BAU: Build model robustness enhancements

- search-config.toml
- train_args.py
- training/train_model.py
- learning rate warm up
- amended dropout 1 proportion to 0.1
- Better predictability results seen from above changes on benchmarks
> Fpo 427 learning rate warm up

- .circleci/bin/smoketest
- Makefile
- flake.nix
- inference/infer.py
- search-config.toml
HMRC-692
- There are situations where vague (normally this means short) search descriptions return 0 results and this is incompatible with how HMRC now want the tool to work to satiate Royal Mail
- All examples we've been given return a good result
- Our benchmarks results do not suddenly plummet
- We've added some test coverage
> HMRC-692: Enhance short description handling

- inference/infer.py
[HMRC-791](https://transformuk.atlassian.net/browse/HMRC-791)
- This has been mandated externally and is not based off of experimentation
- Items scored 10 or less are filtered out of the responses
> BAU: Adjust confidence score cut off

- .github/workflows/deploy-to-production.yml
[HMRC-896](https://transformuk.atlassian.net/browse/HMRC-896)
I have 
- Build stage wasn't working
- Lambda Builds and deploys
> HMRC-896 Fix Deploy To Production

- .github/workflows/bi-weekly-automated-model-build.yml
- .github/workflows/deploy-to-development.yml
[HMRC-978](https://transformuk.atlassian.net/browse/HMRC-978)
> HMRC-978: Fix automated model build workflow

- .github/workflows/deploy-to-development.yml
[HMRC-978](https://transformuk.atlassian.net/browse/HMRC-978)
> HMRC-978: Fix model build trigger

- .github/workflows/deploy-to-development.yml
[HMRC-978](https://transformuk.atlassian.net/browse/HMRC-978)
> HMRC-978: Fix pr number reading

- .github/workflows/deploy-to-development.yml
- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- handler.py
- requirements.txt
- requirements_lambda.txt
- serverless.yml
[HMRC-1153](https://transformuk.atlassian.net/browse/HMRC-1153)
- Sentry is now not used in the service
- I'm tidying up some dead secrets
> HMRC-1153: Removes sentry

- .github/bin/configuregit
- .github/workflows/bi-weekly-automated-model-build.yml
- search-config.toml
[HMRC-1234](https://transformuk.atlassian.net/browse/HMRC-1234)
> HMRC-1234: Fixes permissions when bumping versions for automated build

- search-config.toml
🚀 **What's happening?**
This automated model run has been initiated to incorporate any new data added to the model via the training pipeline's dynamic data sources.
🔔 **Note:**
This pull request will be **closed automatically** once the model run is complete.
Thank you for your patience! 🙌
> 🔄 BAU: Automated model run updated to model version 1.11.7

- .github/workflows/deploy-to-development.yml
[HMRC-1380](https://transformuk.atlassian.net/browse/HMRC-1380)
I have:
> HMRC-1380: Enable e2e tests

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- aws_lambda/handler.py
- benchmark.py
- data_sources/basic_csv.py
- data_sources/search_references.py
- tests/training/test_phrase_remover.py
- training/train_model.py
[HMRC-1458](https://transformuk.atlassian.net/browse/HMRC-1458)
- Ensure production is only deployed after a successful automated staging deployment from the main branch
-
-
-
> HMRC-1458: Update prod deploy triggers

- .github/bin/buildmodel
- reference_data/extra_references.csv
- search-config.toml
[HMRC-1505](https://transformuk.atlassian.net/browse/HMRC-1505)
I have updated codes
> HMRC-1505 Correct codes in extra refs

- search-config.toml
🚀 **What's happening?**
This automated model run has been initiated to incorporate any new data added to the model via the training pipeline's dynamic data sources.
🔔 **Note:**
This pull request will be **closed automatically** once the model run is complete.
Thank you for your patience! 🙌
> 🔄 BAU: Automated model run updated to model version 1.13.2

- .github/benchmark-thresholds.toml
- .github/bin/checkbenchmarks
- .github/bin/smoketest
- .github/bin/validatemodel
- .gitignore
- .pre-commit-config.yaml
- Makefile
- docs/rfcs/001_improve_hierachical_aggregation_in_flat_classifier_with_log_sum_exp.md
- download_transformer.py
- flake.lock
- flake.nix
- inference/infer.py
- reference_data/extra_references.csv
- search-config.toml
[HMRC-1515](https://transformuk.atlassian.net/browse/HMRC-1515)
- This is a prerequisite for improved search results
- Validated a handful of new results are surfaced by the FPO tool
> HMRC-1515: Adds search corrections into extra references

- search-config.toml
🚀 **What's happening?**
This automated model run has been initiated to incorporate any new data added to the model via the training pipeline's dynamic data sources.
🔔 **Note:**
This pull request will be **closed automatically** once the model run is complete.
Thank you for your patience! 🙌
> 🔄 BAU: Automated model run updated to model version 1.16.2
